# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b088958085b1ecdfc728bb96df34e2a6c7ce8a57c8976cbbc904a7b46c627d13b77540c84c44a1556e1f6a968346b0d0d855bb0df4e98b0bf320828003cbaa3

test:
  secret_key_base: df53f8029914850a9047edfee5bdd443dffe023629c4a1779923f4c025a2a2345cbb4c8618f1032b89d3ee03c5927f5e15862265008a1270c8076719393da8ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
